# Course 01-Python for ML : Mid term exam
## Date : 25/10/2025
## Email: subratabaec@gmail.com

In [ ]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


## Question No 01
### -- Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.


In [ ]:
# creating a dataframe
df = pd.read_csv('employees.csv')
print(df)
# df.shape

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR


In [ ]:
# nd array using the df
# array_ages=np.array(df.age)
# array_salaries=np.array(df.salary)

array_ages=np.array(ages)
array_salaries=np.array(salaries)
# print(type(array_ages))

print(array_ages)
print(array_salaries)


[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]


In [ ]:
# age
print(array_ages.dtype)
print(array_ages.ndim)
print(array_ages.shape)
print(array_ages.size)

print("\n")
# salary
print(array_salaries.dtype)
print(array_salaries.ndim)
print(array_salaries.shape)
print(array_salaries.size)

int64
1
(10,)
10


int64
1
(10,)
10


## Question No 02
### -- Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.


In [ ]:
# max salary
max_salary=np.max(array_salaries)
print(f'max: {max_salary}')

# min salary
min_salary=np.min(array_salaries)
print(f'min: {min_salary}')

# avg salary
avg_salary=np.mean(array_salaries)
print(f'avg salary: {avg_salary}')

# avg age
avg_age=np.mean(array_ages)
print(f'avg age: {avg_age}')

max: 89735
min: 30769
avg salary: 57446.9
avg age: 38.5


## Question No 03
### -- From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [ ]:
# print(ages)
# print(array_ages.size) # check original

age_greater_than_30=ages[ages>30]
print(age_greater_than_30)
# print(type(age_greater_than_30)) #check ndarray or not
print(age_greater_than_30.size)


[56 46 32 38 56 36 40]
7


## Question No 04
### -- Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [ ]:
# new age array
modified_ages=ages+5
# print(type(modified_ages))
# print(ages)
print(modified_ages)

[61 51 37 30 43 61 41 45 33 33]


## Question No 05
### -- Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results..

In [ ]:
# print(salaries)
# print(type(salaries))

total_salary=salaries.sum()
print(f"total: {total_salary}")

diff_salary=salaries.max()-salaries.min()
print(f"difference: {diff_salary}")

total: 574469
difference: 58966


## Question No 06
### -- Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().

In [ ]:
# loading dataframe
df = pd.read_csv('employees.csv')
# print(df)
# df.shape

display(df.head(5))
print("\n")

print(df.info())
print("\n")

print(df.describe())

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None


             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


## Question No 07
### -- Display only the id, age, and salary columns. Then show the last 3 rows using tail().

In [ ]:
# print(df.columns)

print(df.loc[:,['id', 'age', 'salary']]) # selecting 3 featues
# print(df.head())
modified_df=df.loc[:,['id', 'age', 'salary']] # creating a anew df with 3 columns
# print(type(modified_df))
modified_df.tail(3)

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311


id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

In [ ]:
# original df tail
# df.tail(3)

## Question No 08
### -- Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.

In [ ]:
IT_df=df.loc[df["dept"]=="IT"] # new df
print(IT_df)
print("\n")

total_IT=len(IT_df)
print(f"total IT: {total_IT}")

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT


total IT: 3


In [ ]:
# df.head()
# len(df)

## Question No 09
### -- Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.

In [ ]:
# df.head()

In [ ]:
# descending order - a new df
dsc_df=df.sort_values(["salary"],ascending=False)
print(dsc_df)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR
1   2   46   74131       IT
3   4   25   71090       IT
2   3   32   46023  Finance
9  10   28   35311       HR
8   9   28   32433    Sales
4   5   38   31685       HR
5   6   56   30769    Sales


In [ ]:
# top 3 employees without id - creating a new df
dsc_df_no_ID=dsc_df.drop("id", axis=1)
dsc_df_no_ID.head(3)

age  salary     dept
6   36   89735  Finance
7   40   86101       IT
0   56   77191       HR

In [ ]:
# dsc_df

## Question No 10
### -- Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.

In [ ]:
# original
df
print(df['salary'].mean())

57446.9


In [ ]:
# salaray>80000  convert to 80000
# original df modifies
df.loc[df["salary"]>80000, "salary"]=80000
df

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
# mean after convertion
print(df["salary"].mean())

55863.3
